# 5.16 ***List 2 Dimensi***
List dua dimensi digunakan untuk menempatkan list didalam list. Biasanya penggambarannya berbentuk matriks

In [ ]:
#Penggambarannya berbentuk matriks
#indeksnya dimulai dari 0
matriks = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
print(matriks)
#hasil yang dikeluarkan berupa baris pada matriks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [ ]:
matriks [1]
#output yang dihasilkan adalah matriks baris 2, karena indeksnya dimulai dari 0

[5, 6, 7, 8]

In [ ]:
matriks [1][2]
#[1] artinya baris yang kedua [5,6,7,8]
#[2] artinya kolom ketiga [7]
# ingat indeks dimulai dari 0

7

In [ ]:
for baris in matriks:
  print(baris)
#mengambil baris di matriks

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


In [ ]:
for kolom in matriks:
  print(kolom)
#mengambil kolom di matriks, hasilnya akan sama seperti mengambil baris

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


In [ ]:
matriks = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
for kolom in matriks:
  print(kolom)#misalkan mengambil kolom di matriks
  for baris in kolom:
    print(baris)#lalu ambil dijadikan baris

[1, 2, 3, 4]
1
2
3
4
[5, 6, 7, 8]
5
6
7
8
[9, 10, 11, 12]
9
10
11
12
[13, 14, 15, 16]
13
14
15
16


# 5.17 ***Tuples***
Hampir sama dengan list akan tetapi tuples tidak dapat dirubah isinya. Jika kita
memiliki data yang tidak ingin dirubah isinya, kita gunakan tuples, sedangkan
jika datanya masih ingin dimanipulasi kedepannya, gunakan list.

In [ ]:
#tuples
huruf = ("a","d","s","a","d","s","e","w","g")
print(huruf[3])#mengambil huruf dengan indeks 3
#indeks dimulai dari 0


a


In [ ]:
#memotong tuple
print(huruf[3:7])
#hasil akan berbentuk kolom atau mendatar
#sama dengan
print(" ")
for abjad in huruf[3:7]:
#hasil akan berbentuk baris atau menurun karena memperjelas huruf apa saja yang ada pada[3:7]
  print(abjad)
#indeks 3 menjadi batas depan dan indeks 6 menjadi batas akhir

('a', 'd', 's', 'e')
 
a
d
s
e


In [ ]:
huruf.count("s")
#untuk mengetahui jumlah data "s"

2

In [ ]:
huruf.append("i")
#error karena data pada tuples tidak dapat dirubah

AttributeError: ignored

In [ ]:
huruf.index("w")
#untuk mengetahui index suatu data

7

In [ ]:
nama =("ni","komang","ari", "asih")
print(nama)
print(nama[3])
print(nama[2:3])
#memotong tuples

('ni', 'komang', 'ari', 'asih')
asih
('ari',)


In [ ]:
nama =("ni","komang","ari", "asih")
#mengambil jumlah nama
print(len(nama))
#megambil panjang tuples

4


In [ ]:
hobi =("Aku suka bermain bulutangkis")
waktu =("sejak aku kecil")
gabungan = (hobi,waktu)
print(gabungan)
#menggabungkan tuples
#penggunaan tuples bisa menggunakan tanda kurung seperti diatas bisa juga tidak
print(" ")
hobi = "Aku suka bermain bulutangkis"
waktu = "sejak aku kecil"
gabungan = (hobi,waktu)
print(gabungan)

('Aku suka bermain bulutangkis', 'sejak aku kecil')
 
('Aku suka bermain bulutangkis', 'sejak aku kecil')


# 5.18 ***Dictionaries***
Dictionaries digunakan jika data nya terkait satu sama lain.

In [ ]:
Identitas = {
    "Nama" : "Ariasih",
    "Usia" : 19,
}
print(Identitas["Nama"])
print(Identitas.get("Nama"))
print(Identitas.get("nama"))#hasilnya tidak ada, karena tidak ada "nama" huruf depannya ditulis menggunakan kapital
print(Identitas["Usia"])
print(Identitas.get("tanggal lahir"))#hasilnya tidak ada, karena tidak ada variabrel tanggal lahir
print(Identitas.get("tanggal lahir", "16-10-2003"))#mencoba menambahkan tanggal lahir
print(Identitas)
print(Identitas.get("NIM"))#tidak ada, karena tidak ada variabel nim
print(Identitas.get("NIM", "2208541002"))#mencoba menambahkan nim
print(Identitas)
#bermaksud untuk menambah nilai, tapi ternyata tidak bisa

Ariasih
Ariasih
None
19
None
16-10-2003
{'Nama': 'Ariasih', 'Usia': 19}
None
2208541002
{'Nama': 'Ariasih', 'Usia': 19}


In [ ]:
#menambah dan mengubah nilai
mahasiswa = {
  'nama'  : 'Ariasih',
  'kelas' : 'A',
  'umur'  : 19,
  'alamat': 'Jl. nin aja dulu',
}
#menambah nilai
#memasukkan nilai yang ingin ditambahkan, lalu program di print
mahasiswa['nim'] = '2208541002'
print(mahasiswa)
print(" ")
#mengubah nilai
#masukkan data yang ingin diubah
mahasiswa["alamat"] = 'Jl. Goa Gong'
print(mahasiswa)

{'nama': 'Ariasih', 'kelas': 'A', 'umur': 19, 'alamat': 'Jl. nin aja dulu', 'nim': '2208541002'}
 
{'nama': 'Ariasih', 'kelas': 'A', 'umur': 19, 'alamat': 'Jl. Goa Gong', 'nim': '2208541002'}


In [ ]:
#menghapus nilai
#Untuk menghapus nilai dictionary ada 2 cara yaitu menggunakan statement del atau dengan fungsi pop()
mahasiswa = {
  'nama'  : 'Ariasih',
  'kelas' : 'A',
  'umur'  : 19,
  'alamat': 'Jl. Goa Gong',
}

# dengan statement del
del mahasiswa['nama']
print(mahasiswa)
# dengan fungsi pop()
mahasiswa.pop('kelas')
print(mahasiswa)


{'kelas': 'A', 'umur': 19, 'alamat': 'Jl. Goa Gong'}
{'umur': 19, 'alamat': 'Jl. Goa Gong'}


In [ ]:
#mengetahui banyaknya nilai yang terdapat pada dictionary dengan menggunakan fungsi len()
mahasiswa = {
  'nama'  : 'Ariasih',
  'kelas' : 'A',
  'umur'  : 19,
  'alamat': 'Jl. nin aja dulu',
}
print('mahasiswa: {}'.format(len(mahasiswa)))

mahasiswa: 4


In [ ]:
#mengubah angka menjadi sebutan bilangan tersebut
Angka = {
    "0" : "Nol",
    "1" : "Satu",
    "2" : "Dua",
    "3" : "Tiga",
    "4" : "Empat",
    "5" : "Lima",
    "6" : "Enam",
    "7" : " Tujuh",
    "8" : "Delapan"
}
NIM = input("NIM saya adalah " )
nomor_Angka = " "
for isi in NIM:
  nomor_Angka += Angka.get(isi) + " "
print(nomor_Angka)

NIM saya adalah 2208541002
 Dua Dua Nol Delapan Lima Empat Satu Nol Nol Dua 


# 5.19 ***Fungsi dalam Python***
Jenis fungsi pada Python seperti fungsi input, print, len, range, dll. Pada dasarnya fungsi dibentuk untuk menghindari pengulangan pembuatan program secara manual.

In [ ]:
#fungsi dalam phyton
def full_name(first_name, last_name):
  print(f"Nama lengkap adalah {first_name} {last_name}")
#mendefinisikan program yang akan dibuat dan hasil yang dikeluarkan

In [ ]:
def full_name(first_name, last_name):
  print(f"Nama lengkap adalah {first_name} {last_name}")
first_name = input("Hai namaku ")#input nama depan
last_name = input("Nama belakangku ")#input nama belakang
full_name(first_name,last_name)

Hai namaku Arii
Nama belakangku asih
Nama lengkap adalah Arii asih


In [ ]:
#menghitung luas persegi panjang
#rumus luas persegi adalah SxS
sisi = input("panjang sisi persegi adalah ")
luas = int(sisi)* int(sisi)
print(luas)
#bisa juga tanpa definisi, karena tadi menggunakan definisi hasilnya error maka menggunakan fungsi print

panjang sisi persegi adalah 3
9


**5.19.1 Tugas Fungsi pada Python**

Ada dua jenis tugas fungsi pada Python yaitu:
 Menjalankan perintah.
 Menampilkan hasil perhitungan

In [ ]:
#Tugas Fungsi pada Python
#Menjalankan perintah
def waktu_sampai(jarak,kecepatan):
  waktu = jarak/kecepatan
  print(waktu)
#melakukan print dari hasil pemrosesan secara langsung di dalam fungsinya.
jarak = input(" ")
kecepatan = input(" ")
waktu_sampai = int(jarak)/ int(kecepatan)
print(waktu_sampai)

#menampilkan hasil perhitungan
print(" ")
def waktu_sampai(jarak,kecepatan):
  waktu = jarak/kecepatan
  return (waktu)
#melakukan print pada saat pemanggilannya.
jarak = input(" ")
kecepatan = input(" ")
waktu_sampai = int(jarak)/ int(kecepatan)
print(waktu_sampai)#pemanggilan fungsi

 100
 35
2.857142857142857
 
 100
 35
2.857142857142857


In [ ]:
#luas segitiga
def luas_segitiga(alas, tinggi):
    luas = (alas * tinggi) / 2
    print(luas)
alas =input("alas suatu segitiga adalah ")
tinggi = input("tinggi dari suatu segitiga adalah ")
luas = (int(alas)* int(tinggi) / 2)
print("luas suatu segitiga adalah ", luas)

print(" ")
#pemanfaatan fungsi return (melakukan print saat pemanggilan) untuk mencari volume 
# rumus: sisi x sisi
def luas_persegi(sisi):
    luas = sisi * sisi
    return luas
# rumus: sisi x sisi x sisi
def volume_persegi(sisi):
    volume = luas_persegi(sisi) * sisi

sisi = input("panjang sisi persegi adalah ")
luas_persegi = int(sisi)* int(sisi)
volume_persegi = (luas_persegi* int(sisi))
print(volume_persegi)

alas suatu segitiga adalah 8
tinggi dari suatu segitiga adalah 12
luas suatu segitiga adalah  48.0
 
panjang sisi persegi adalah 3
27


In [ ]:
#latihan fungsi dalam phyton
jenis_bidang = input("Jenis bidang adalah ")
if jenis_bidang.upper()=="SEGITIGA":
  alas = float(input("panjang alasnya adalah "))
  tinggi = float(input("tinggi segitiga ini adalah "))
  luas = (int(alas)*int(tinggi)/2)
  print(f"luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper()=="PERSEGI PANJANG":
  panjang = float(input("panjangnya adalah "))
  lebar = float(input("lebarnya adalah "))
  luas = luas_persegi_panjang(panjang,lebar)
  print(f"luas {jenis_bidang} adalah {luas}")
else:
  print(f"Maaf bidang {jenis_bidang} yang dimasukkan tidak ada.")
  print("pilihan cuman segitiga dan persegi panjang")
  print("terimakasih")

print(" ")
jenis_bidang = input("Jenis bidang adalah ")
if jenis_bidang.upper()=="SEGITIGA":
  alas = float(input("panjang alasnya adalah "))
  tinggi = float(input("tinggi segitiga ini adalah "))
  luas = luas_segitiga(alas,tinggi)
  print(f"luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper()=="PERSEGI PANJANG":
  panjang = float(input("panjangnya adalah "))
  lebar = float(input("lebarnya adalah "))
  luas = luas_persegi_panjang(panjang,lebar)
  print(f"luas {jenis_bidang} adalah {luas}")
else:
  print(f"Maaf bidang {jenis_bidang} yang dimasukkan tidak ada.")
  print("pilihan cuman segitiga dan persegi panjang")
  print("terimakasih")

Jenis bidang adalah segitiga
panjang alasnya adalah 5
tinggi segitiga ini adalah 10
luas segitiga adalah 25.0
 
Jenis bidang adalah persegi
Maaf bidang persegi yang dimasukkan tidak ada.
pilihan cuman segitiga dan persegi panjang
terimakasih


# 5.20 ***Numpy***
Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan
dalam perhitungan menggunakan vektor dam matrik dalam berbagai dimensi.
Indeks dimulai dari 0

In [ ]:
import numpy
#memanggil library numpy

**5.20.1 Perintah Dasar pada Numpy**

In [ ]:
#fungsi pemanggil numpy
a = numpy.array([0,1,2,3,4])
print(a)
print(" ")
b = numpy.array([[5,6,7,8], [9,10,11,12]])
print(b)
print(" ")
c = numpy.array([[[0,1,2,3,4],[5,6,7,8,9]],
                [[8,9,10,11,12],[2,4,5,7,6]],
                [[1,2,3,4,5], [6,7,8,9,10]]])
print(c)

[0 1 2 3 4]
 
[[ 5  6  7  8]
 [ 9 10 11 12]]
 
[[list([0, 1, 2, 3, 4]) list([5, 6, 7, 8, 9])]
 [list([9, 10, 11, 12]) list([2, 4, 5, 7, 6])]
 [list([1, 2, 3, 4, 5]) list([6, 7, 8, 9, 10])]]


<ipython-input-18-0f988c9f801f>:13: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c = numpy.array([[[0,1,2,3,4],[5,6,7,8,9]],


In [ ]:
#fungsi untuk mengetahui dimensi pada array
print(a.ndim)
print(b.ndim)
print(c.ndim)
#fungsi untuk mengetahui ukuran variabel atau panjang dimensi
print(a.shape)
print(b.shape)
print(c.shape)

1
2
2
(5,)
(2, 4)
(3, 2)


In [ ]:
import numpy

**5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy**

In [ ]:
n = numpy.array([[5,6,7,8], [9,10,11,12]])
print(b)

print(n[0,3])#ingin mendapatkan data pertama dan kolom ke-3

print(n[1,2])#ingin mendapatkan data kedua dan kolom ke-2

print(n[1,:])#ingin mendapatkan data kedua

print(n[ :,2])#ingin mendapatkan indeks kedua pada data pertama dan kedua

print(n[1,1:3])#ingin mendapatkan data kedua indeks ke 1 sampai 3

print(n[0,0:3:2])#sama seperti diatas, namun angka 2 paling belakang mendefinisikan loncat 2 kali

n[0,0] = 20 #mengubah indeks pada data pertama
print(n)


15
8
11
[ 9 10 11 12]
[ 7 11]
[10 11]
[5 7]
[[20  6  7  8]
 [ 9 10 11 12]]


**5.20.3 Matrix pada Numpy**

In [ ]:
#cara membuat matriks
o = numpy.zeros((10,10))#matriks semua entrynya 0
print(o)
print(" ")
p = numpy.ones((3,3))#matriks semua entrynya 1
print(p)
print(" ")
q = numpy.identity(4)#membuat matriks identitas
print(q)
print(" ")
r = numpy.full((4,5),6)#matriks 4x5 dengan entrynya semua 6
print(r)
print(" ")
s = numpy.random.rand(4,4)
print(s)
print(" ")
t = numpy.random.randint(1,5, size=(3,3))#matriks random dengan nilai entry yang sudah ditentukan
print(t)
print(" ")
#membuat matriks dengan menggabungkan 2 array
a1 = numpy.array([1,2,3])
a2 = numpy.array([4,5,6])
matriks = numpy.array([a1,a2])
print(matriks)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
 
[[0.54347056 0.30503471 0.63506386 0.80892187]
 [0.28370824 0.51596    0.55720702 0.66212675]
 [0.62788205 0.99270393 0.72427549 0.94775834]
 [0.72634564 0.55158369 0.23336117 0.98101287]]
 
[[1 1 2]
 [1 2 2]
 [3 3 4]]
 
[[1 2 3]
 [4 5 6]]


**5.20.4 Copy pada Numpy**

Saat anggota variabel baru dirubah,
dampaknya juga akan merubah variabel asal. Untuk menghindari perubahan
variabel awal yang tidak dikehendaki maka diperlukan perintah copy 

In [ ]:
A = numpy.array([1,2,3,4,5])
print(A)
print(" ")
B = A #mendefinisikan B sama dengan A
print(B)
print(" ")
B[0] = 10 #mengubah indeks ke 0 menjadi 10
print(B)
print(" ")
print(A)#definisi B sama dengan A tidak berubah
print(" bandingkan dengan yang dibawah ini")
C = numpy.array([1,2,3,4,5])
print(C)
print(" ")
D = C.copy()
print(D)
print(" ")
D[0] = 10
print(D)
print(" ")
print(C)#nilai C tidak akan berubah, karena C tidak sama dengan D

[1 2 3 4 5]
 
[1 2 3 4 5]
 
[10  2  3  4  5]
 
[10  2  3  4  5]
 bandingkan dengan yang dibawah ini
[1 2 3 4 5]
 
[1 2 3 4 5]
 
[10  2  3  4  5]
 
[1 2 3 4 5]


**5.20.5 Operasi Matematika pada Numpy**

In [ ]:
v = numpy.array([1,2,3,4,0])
print(v-2)#pengurangan
print(v+4)#penjumlahan
print(v*2)#perkalian
print(v/2)#pembagian
print(v**2)#perpangkatan
print(" ")
print(" trigonometri")
cos=  numpy.cos(v)
print(cos)
sin = numpy.sin(v)
print(sin)
cosh = numpy.cosh(v)
print(cosh)
sinh = numpy.sinh(v)
print(sinh)
tan = numpy.tan(v)
print(tan)
tanh = numpy.tanh(v)
print(tanh)
sqrt = numpy.sqrt(v)
print(sqrt)


[-1  0  1  2 -2]
[5 6 7 8 4]
[2 4 6 8 0]
[0.5 1.  1.5 2.  0. ]
[ 1  4  9 16  0]
 
 trigonometri
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  1.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025   0.        ]
[ 1.54308063  3.76219569 10.067662   27.30823284  1.        ]
[ 1.17520119  3.62686041 10.01787493 27.2899172   0.        ]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128  0.        ]
[0.76159416 0.96402758 0.99505475 0.9993293  0.        ]
[1.         1.41421356 1.73205081 2.         0.        ]


In [ ]:
#operasi pada 2 matriks
mat1 = numpy.array([1,2,3,4,5])
mat2 = numpy.array([5,6,7,8,9])
print(mat1-mat2)
print(mat1+mat2)
print(mat2**mat1)

[-4 -4 -4 -4 -4]
[ 6  8 10 12 14]
[    5    36   343  4096 59049]


**5.20.6 Perkalian Matrik pada Numpy**

Perkalian matrik pada Numpy dapat menggunakan perintah matmul

In [ ]:
u1 = numpy.array([[1,2,3,4,5],[0,1,2,3,4]])
print(u1)
print(" ")
u2 = numpy.array([[5,6,7,8,9], [1,5,6,7,8]])
print(u2)
print(" ")
u3 = u1*u2
print(u3)
print(" ")
#ukuran matrik yang akan dikalikan harus sesuai dengan persyaratan
u4 = numpy.matmul(u1,u2) #sedangkam matriks ini tidak memenuhi syarat
print(u4)

[[1 2 3 4 5]
 [0 1 2 3 4]]
 
[[5 6 7 8 9]
 [1 5 6 7 8]]
 
[[ 5 12 21 32 45]
 [ 0  5 12 21 32]]
 


ValueError: ignored

In [ ]:
#penggunaan fungsi matmul
A1 = numpy.array ([[5, 0],
                  [0, 5]])
B1 = numpy.array ([5, 2])
C1 = numpy.matmul(A1,B1)
print(C1)
print(" ")
#perbandingannya dibandingkan kali biasa
D1 = A1*B1
print(D1)

[25 10]
 
[[25  0]
 [ 0 10]]


**5.20.7 min, max dan sum pada Numpy**

Digunakan untuk mengetahui nilai
minimum, maksimum dan penjumlahan

In [ ]:
a = numpy.array([[1,2,3,4],
                [5,6,7,8],
                [9,1,2,4]])
print(a)
print(" ")
b = numpy.min(a)#mencari nilai minimum
print(b)
print(" ")
c = numpy.min(a,axis=0)
print(c)
print(" ")
d = numpy.min(a,axis=1)
print(d)
print(" ")
e = numpy.max(a)#mencari nilai maximum
print(e)
print(" ")
f = numpy.max(a,axis=0)
print(f)
print(" ")
g = numpy.max(a,axis=1)
print(g)
print(" ")
h = numpy.sum(a)#penjumlahan
print(h)
print(" ")
i = numpy.sum(a,axis=0)
print(i)
print(" ")
j = numpy.sum(a,axis=1)
print(j)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 4]]
 
1
 
[1 1 2 4]
 
[1 5 1]
 
9
 
[9 6 7 8]
 
[4 8 9]
 
52
 
[15  9 12 16]
 
[10 26 16]


In [ ]:
from ast import Yield
#contoh 2
X = numpy.array([1,3,5,9,7,15])
print(X)
Y = numpy.max(X)
print(Y)
Z = numpy.min(X)
print(Z) 
W = numpy.sum(X)
print(W)

[ 1  3  5  9  7 15]
15
1
40
